from Pessoa import Pessoa
p1 = Pessoa('Gabriel', 19)
p2 = Pessoa('maria',13)
p1.comer('uva')
p1.falar('POO')
p1.parar_de_comer()
p1.falar('POO')
p1.parar_falar()
p1.comer('uva')
p2.falar('Ala')
p2.comer('churrasco')
print(p1.get_ano_nascimento())
print(Pessoa.gera_id())
print(p1.gera_id())
